FROM python:3.12.5-slim

RUN apt update && apt install -y git
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt

RUN mkdir -p /app
WORKDIR /app