FROM --platform=linux/amd64 python:3.12.5-slim AS build

RUN apt update && \
    apt install -y wget && \
    mkdir -p /crt && \
    wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt && \
    chmod 0600 /crt/YandexInternalRootCA.crt

ARG KAFKA_HOST
ARG KAFKA_PORT
ARG KAFKA_CONSUMER_USERNAME
ARG KAFKA_CONSUMER_PASSWORD
ARG KAFKA_CONSUMER_GROUP
ARG KAFKA_SOURCE_TOPIC
ARG KAFKA_DESTINATION_TOPIC

ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD

ARG PG_WAREHOUSE_HOST
ARG PG_WAREHOUSE_PORT
ARG PG_WAREHOUSE_DBNAME
ARG PG_WAREHOUSE_USER
ARG PG_WAREHOUSE_PASSWORD

ARG BATCH_SIZE

COPY . .

RUN pip install -r requirements.txt

WORKDIR /src

ENTRYPOINT ["python"]
CMD ["app.py"]